# This workflow will build and test the project

name: build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        configuration: [Debug, Release]

    runs-on: ${{ matrix.os }}

    env:
      Solution_Name: ./src/Eppie.CLI/Eppie.CLI.sln
      Project_Name: ./src/Eppie.CLI/Eppie.CLI/Eppie.CLI.csproj
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - run: dotnet --info
    
    - run: echo "$PWD"
      shell: bash

    # Build the solution
    - name: Build the solution
      run: dotnet build $env:Project_Name --nologo --configuration $env:Configuration -v d
      env:
        Configuration: ${{ matrix.configuration }}
        
    # Execute all unit tests
    - name: Execute unit tests
      run: dotnet test $env:Project_Name --nologo --configuration $env:Configuration 
      env:
        Configuration: ${{ matrix.configuration }}
