# This workflow will publish the project

name: Publish

on:
  workflow_dispatch:
    inputs:
      config-file:
        type: string
        default: "./publish/config.json"

      target-os:
        type: choice
        default: all
        options: 
        - windows
        - linux
        - macos
        - all

      target-runtime:
        type: choice
        default: all
        options: 
        - x86
        - x64
        - arm
        - arm64
        - all

env:
  dotnet-version: 8.x
        
jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.publish-config-parser.outputs.profiles }}
      status: ${{ steps.checker.outputs.status }}
      project-file: ${{ steps.publish-config-parser.outputs.project-file }}
      output-name: ${{ steps.publish-config-parser.outputs.output-name }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Parse configuration "${{ github.event.inputs.config-file }}"
      id: publish-config-parser
      uses: ./.github/actions/publish-config-parser
      with:
        config-file: ${{ github.event.inputs.config-file }}
        tags: "${{ github.event.inputs.target-os }},${{ github.event.inputs.target-runtime }}"

    - name: Check profiles
      id: checker
      run: |
        profiles='${{ steps.publish-config-parser.outputs.profiles }}'
        length=$( echo $profiles | jq '.include | length' )

        if(( $length > 0 )); then
           echo "status=success" >> $GITHUB_OUTPUT
         else
           echo "status=failure" >> $GITHUB_OUTPUT
           echo "No suitable publish profile found"
         fi
    
  publish:
    name: Publish
    needs: prepare
    if: needs.prepare.outputs.status == 'success'
    
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{fromJson(needs.prepare.outputs.matrix)}}

    env:
      output-name: ${{ needs.prepare.outputs.output-name }}
      project-file: ${{ needs.prepare.outputs.project-file }}
      configuration: ${{ matrix.configuration }}
      framework: ${{ matrix.framework }}
      runtime: ${{ matrix.runtime }}
      publish-options: ${{ matrix.options }}
      output-root: publish/output

      # template: root/configuration/framework/runtime
      output-template: '{0}/{1}/{2}/{3}'
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.dotnet-version }}

    - id: version-number
      uses: finebits/github-actions/version-number@v1

    - name: Publish ${{ env.output-name }} [${{ env.version-short }}]
      run: |
        dotnet publish "${{ env.project-file }}" --output "${{ env.output }}" --configuration "${{ env.configuration }}" --framework "${{ env.framework }}" --runtime "${{ env.runtime }}" --property:Version="${{ env.version-full }}" ${{ env.publish-options }} 
      env:
        output: "${{ format(env.output-template, env.output-root, env.configuration, env.framework, env.runtime) }}"
        version-full: "${{ steps.version-number.outputs.suffix-githash-version }}"
        version-short: "${{ steps.version-number.outputs.suffix-version }}"

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: "${{ env.output-name }}-${{ env.runtime }} [${{ env.version-short }}]"
        path: "${{ env.path }}"
      env:
        artifact-name: "${{ env.output-name }}"
        version-short: "${{ steps.version-number.outputs.suffix-version }}"
        path: "${{ format(env.output-template, env.output-root, env.configuration, env.framework, env.runtime) }}"


  upload-assets:
    name: Upload Assets
    if: github.event_name == 'release'
    needs: publish
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        merge-multiple: true
        
    - run: ls -R artifacts
    
    - shell: bash
      run: | 
        cd "artifacts"
        url="${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/releases/tags/${GITHUB_REF_NAME}"
        echo "url: $url"
        response=$(curl --request "GET" \
                        --silent \
                        --location \
                        --header "Accept: application/vnd.github+json" \
                        --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                        --header "X-GitHub-Api-Version: 2022-11-28" \
                        "$url")

        release_url=$(echo "$response" | jq -r ".url")
        upload_url=$(echo "$response" | jq -r ".upload_url")
        release_id=$(echo "$response" | jq -r ".id")

        echo "release_url: $release_url"
        echo "release_id: $release_id"
        echo "upload_assets_url: $upload_url"

        for file in *; do
          echo "file: $file"
          if test -f "$file"; then
            upload_file_url="${upload_url%{*}?name=$file"
            echo "upload_url: $upload_file_url"

            response=$(curl --request "POST" \
                            --location \
                            --header "Accept: application/vnd.github+json" \
                            --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                            --header "X-GitHub-Api-Version: 2022-11-28" \
                            --header "Content-Type: application/zip" \
                            --data-binary "@$file" \
                            "$upload_file_url")

            echo "upload response: $response"
          fi
        done
